# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id_bloq', models.AutoField(primary_key=True, serialize=False)),
                ('bloq_tiempo', models.FloatField(unique=True)),
            ],
            options={
                'db_table': 'bloque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_prd', models.AutoField(primary_key=True, serialize=False)),
                ('prd_inicio', models.TimeField()),
                ('prd_fin', models.TimeField()),
            ],
            options={
                'db_table': 'periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_us', models.AutoField(primary_key=True, serialize=False)),
                ('us_nombre', models.CharField(max_length=45)),
                ('us_apat', models.CharField(max_length=25)),
                ('us_amat', models.CharField(max_length=25)),
                ('us_slug', models.CharField(max_length=10, unique=True)),
                ('us_user', models.CharField(max_length=15, unique=True)),
                ('us_pass', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
