# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('event_inicio', models.DateTimeField()),
                ('event_fin', models.DateTimeField()),
                ('event_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
    ]
