-- MySQL Script generated by MySQL Workbench
-- mar 22 mar 2016 15:36:16 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agendaDicyg
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agendaDicyg` ;

-- -----------------------------------------------------
-- Schema agendaDicyg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agendaDicyg` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `agendaDicyg` ;

-- -----------------------------------------------------
-- Table `agendaDicyg`.`bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaDicyg`.`bloque` (
  `id_bloq` INT NOT NULL AUTO_INCREMENT,
  `bloq_tiempo` FLOAT NOT NULL,
  PRIMARY KEY (`id_bloq`),
  UNIQUE INDEX `bloq_tiempo_UNIQUE` (`bloq_tiempo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agendaDicyg`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaDicyg`.`usuario` (
  `id_us` INT NOT NULL AUTO_INCREMENT,
  `id_bloq` INT NOT NULL,
  `us_nombre` VARCHAR(45) NOT NULL,
  `us_apat` VARCHAR(25) NOT NULL,
  `us_amat` VARCHAR(25) NOT NULL,
  `us_slug` VARCHAR(10) NOT NULL,
  `us_user` VARCHAR(15) NOT NULL,
  `us_pass` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_us`),
  INDEX `fk_usuario_bloque_idx` (`id_bloq` ASC),
  UNIQUE INDEX `us_user_UNIQUE` (`us_user` ASC),
  UNIQUE INDEX `us_slug_UNIQUE` (`us_slug` ASC),
  CONSTRAINT `fk_usuario_bloque`
    FOREIGN KEY (`id_bloq`)
    REFERENCES `agendaDicyg`.`bloque` (`id_bloq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agendaDicyg`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaDicyg`.`persona` (
  `id_per` INT NOT NULL AUTO_INCREMENT,
  `per_id` VARCHAR(25) NOT NULL,
  `per_nombre` VARCHAR(45) NOT NULL,
  `per_apat` VARCHAR(25) NOT NULL,
  `per_amat` VARCHAR(25) NOT NULL,
  `per_email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_per`),
  UNIQUE INDEX `per_id_UNIQUE` (`per_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agendaDicyg`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaDicyg`.`evento` (
  `id_event` INT NOT NULL AUTO_INCREMENT,
  `id_us` INT NOT NULL,
  `id_per` INT NOT NULL,
  `event_inicio` DATETIME NOT NULL,
  `event_fin` DATETIME NOT NULL,
  `event_descripcion` TEXT NULL,
  PRIMARY KEY (`id_event`),
  INDEX `fk_evento_usuario1_idx` (`id_us` ASC),
  INDEX `fk_evento_persona1_idx` (`id_per` ASC),
  CONSTRAINT `fk_evento_usuario1`
    FOREIGN KEY (`id_us`)
    REFERENCES `agendaDicyg`.`usuario` (`id_us`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_persona1`
    FOREIGN KEY (`id_per`)
    REFERENCES `agendaDicyg`.`persona` (`id_per`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agendaDicyg`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendaDicyg`.`periodo` (
  `id_prd` INT NOT NULL AUTO_INCREMENT,
  `id_us` INT NOT NULL,
  `prd_inicio` TIME NOT NULL,
  `prd_fin` TIME NOT NULL,
  PRIMARY KEY (`id_prd`),
  INDEX `fk_periodo_usuario1_idx` (`id_us` ASC),
  CONSTRAINT `fk_periodo_usuario1`
    FOREIGN KEY (`id_us`)
    REFERENCES `agendaDicyg`.`usuario` (`id_us`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `agendaDicyg`.`bloque`
-- -----------------------------------------------------
START TRANSACTION;
USE `agendaDicyg`;
INSERT INTO `agendaDicyg`.`bloque` (`id_bloq`, `bloq_tiempo`) VALUES (1, 0.5);
INSERT INTO `agendaDicyg`.`bloque` (`id_bloq`, `bloq_tiempo`) VALUES (2, 1);

COMMIT;

