-- MySQL Script generated by MySQL Workbench
-- dom 13 mar 2016 22:36:52 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agendaDicyg
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agendaDicyg` ;

-- -----------------------------------------------------
-- Schema agendaDicyg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agendaDicyg` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `agendaDicyg` ;

-- -----------------------------------------------------
-- Table `agendaDicyg`.`bloque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agendaDicyg`.`bloque` ;

CREATE TABLE IF NOT EXISTS `agendaDicyg`.`bloque` (
  `id_bloque` INT NOT NULL AUTO_INCREMENT,
  `bloq_tiempo` FLOAT NOT NULL,
  PRIMARY KEY (`id_bloque`),
  UNIQUE INDEX `bloq_tiempo_UNIQUE` (`bloq_tiempo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agendaDicyg`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agendaDicyg`.`usuario` ;

CREATE TABLE IF NOT EXISTS `agendaDicyg`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `us_nombre` VARCHAR(45) NOT NULL,
  `us_apat` VARCHAR(45) NOT NULL,
  `us_amat` VARCHAR(45) NOT NULL,
  `us_user` VARCHAR(45) NOT NULL,
  `us_pass` VARCHAR(33) NOT NULL,
  `id_bloque` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_bloque_idx` (`id_bloque` ASC),
  UNIQUE INDEX `us_user_UNIQUE` (`us_user` ASC),
  CONSTRAINT `fk_usuario_bloque`
    FOREIGN KEY (`id_bloque`)
    REFERENCES `agendaDicyg`.`bloque` (`id_bloque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agendaDicyg`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agendaDicyg`.`persona` ;

CREATE TABLE IF NOT EXISTS `agendaDicyg`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `per_id` VARCHAR(45) NULL,
  `per_nombre` VARCHAR(45) NULL,
  `per_apat` VARCHAR(45) NULL,
  `per_amat` VARCHAR(45) NULL,
  `per_email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agendaDicyg`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agendaDicyg`.`evento` ;

CREATE TABLE IF NOT EXISTS `agendaDicyg`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `event_inicio` DATETIME NOT NULL,
  `event_fin` DATETIME NOT NULL,
  `event_descripcion` TEXT NULL,
  PRIMARY KEY (`id_evento`),
  INDEX `fk_evento_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_evento_persona1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_evento_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `agendaDicyg`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `agendaDicyg`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agendaDicyg`.`periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agendaDicyg`.`periodo` ;

CREATE TABLE IF NOT EXISTS `agendaDicyg`.`periodo` (
  `id_periodo` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `prd_inicio` TIME NOT NULL,
  `prd_fin` TIME NOT NULL,
  PRIMARY KEY (`id_periodo`),
  INDEX `fk_periodo_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_periodo_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `agendaDicyg`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `agendaDicyg`.`bloque`
-- -----------------------------------------------------
START TRANSACTION;
USE `agendaDicyg`;
INSERT INTO `agendaDicyg`.`bloque` (`id_bloque`, `bloq_tiempo`) VALUES (, 0.5);
INSERT INTO `agendaDicyg`.`bloque` (`id_bloque`, `bloq_tiempo`) VALUES (, 1);

COMMIT;

